Name:           ros-kinetic-ethercat-hardware
Version:        1.8.18
Release:        1%{?dist}
Summary:        ROS ethercat_hardware package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/ethercat_hardware
Source0:        %{name}-%{version}.tar.gz

Requires:       log4cxx-devel
Requires:       ros-kinetic-diagnostic-msgs
Requires:       ros-kinetic-diagnostic-updater
Requires:       ros-kinetic-eml
Requires:       ros-kinetic-message-runtime
Requires:       ros-kinetic-pluginlib
Requires:       ros-kinetic-pr2-hardware-interface
Requires:       ros-kinetic-pr2-msgs
Requires:       ros-kinetic-realtime-tools
Requires:       ros-kinetic-roscpp
BuildRequires:  log4cxx-devel
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-diagnostic-msgs
BuildRequires:  ros-kinetic-diagnostic-updater
BuildRequires:  ros-kinetic-eml
BuildRequires:  ros-kinetic-message-generation
BuildRequires:  ros-kinetic-pluginlib
BuildRequires:  ros-kinetic-pr2-hardware-interface
BuildRequires:  ros-kinetic-pr2-msgs
BuildRequires:  ros-kinetic-realtime-tools
BuildRequires:  ros-kinetic-roscpp

%description
Package for creating a hardware interface to the robot using the EtherCAT motor
controller/driver

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Fri Apr 13 2018 David Feil-Seifer <dave@cse.unr.edu> - 1.8.18-1
- Autogenerated by Bloom

